#!/usr/bin/env python3
"""grid_to_world.py - build a Gazebo world whose walls ARE drive 10's saved 2D map (dry-run only).

Every occupied 5 cm cell of the exported map (maps/d10_nav.pgm + .yaml) becomes part of a 1.2 m tall static box.
Neighbouring cells are merged into rectangles (greedy: extend right, then up) so Gazebo gets a few thousand boxes,
not tens of thousands. Isolated specks (an occupied cell with fewer than MIN_NEIGH occupied neighbours) are dropped:
they are depth noise in the camera map and would only become 5 cm pillars in the simulation.

*Plain terms: the simulated building is drive 10's floor plan pulled up into walls, so the dry run drives the same
corridors, with the same widths, that the real robot will.*

What this world is NOT: the real building. The walls sit exactly where the map says, so the simulated robot's map
and world agree perfectly; the real run will not have that luxury. The dry run tests the planner, the costmaps and
the command chain, not the localisation.

usage:  grid_to_world.py ../maps/d10_nav.yaml d10_floor.world
"""
import os
import sys

import numpy as np

MIN_NEIGH = 2
HEIGHT = 1.2


def load_map(yaml_path):
    meta = {}
    for line in open(yaml_path):
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    res = float(meta["resolution"])
    ox, oy = [float(t) for t in meta["origin"].strip("[]").split(",")[:2]]
    pgm = os.path.join(os.path.dirname(yaml_path), meta["image"])
    with open(pgm, "rb") as f:
        assert f.readline().strip() == b"P5"
        line = f.readline()
        while line.startswith(b"#"):
            line = f.readline()
        w, h = [int(t) for t in line.split()]
        f.readline()
        img = np.frombuffer(f.read(w * h), dtype=np.uint8).reshape(h, w)
    occ = np.flipud(img) == 0          # row 0 = lowest y again
    return occ, res, ox, oy


def clean(occ):
    p = np.pad(occ, 1).astype(np.int8)
    n = sum(np.roll(np.roll(p, dy, 0), dx, 1) for dy in (-1, 0, 1) for dx in (-1, 0, 1)
            if (dy, dx) != (0, 0))[1:-1, 1:-1]
    return occ & (n >= MIN_NEIGH)


def rectangles(occ):
    used = np.zeros_like(occ)
    H, W = occ.shape
    out = []
    for r in range(H):
        c = 0
        while c < W:
            if occ[r, c] and not used[r, c]:
                c2 = c
                while c2 + 1 < W and occ[r, c2 + 1] and not used[r, c2 + 1]:
                    c2 += 1
                r2 = r
                while r2 + 1 < H and occ[r2 + 1, c:c2 + 1].all() and not used[r2 + 1, c:c2 + 1].any():
                    r2 += 1
                used[r:r2 + 1, c:c2 + 1] = True
                out.append((r, c, r2, c2))
                c = c2 + 1
            else:
                c += 1
    return out


def main():
    occ, res, ox, oy = load_map(sys.argv[1])
    kept = clean(occ)
    rects = rectangles(kept)
    links = []
    for i, (r, c, r2, c2) in enumerate(rects):
        sx, sy = (c2 - c + 1) * res, (r2 - r + 1) * res
        cx, cy = ox + (c + c2 + 1) * res / 2.0, oy + (r + r2 + 1) * res / 2.0
        geom = "<box><size>%.3f %.3f %.2f</size></box>" % (sx, sy, HEIGHT)
        links.append(
            "      <link name='w%d'><pose>%.3f %.3f %.2f 0 0 0</pose>"
            "<collision name='c'><geometry>%s</geometry></collision>"
            "<visual name='v'><geometry>%s</geometry><material><ambient>0.6 0.6 0.6 1</ambient>"
            "<diffuse>0.7 0.7 0.7 1</diffuse></material></visual></link>" % (i, cx, cy, HEIGHT / 2, geom, geom))
    world = """<?xml version="1.0"?>
<!-- generated by grid_to_world.py from %s: %d occupied cells (%d after dropping specks) -> %d boxes -->
<sdf version="1.6">
  <world name="d10_floor">
    <include><uri>model://sun</uri></include>
    <include><uri>model://ground_plane</uri></include>
    <physics type="ode"><max_step_size>0.001</max_step_size><real_time_update_rate>1000</real_time_update_rate></physics>
    <model name="d10_walls">
      <static>true</static>
%s
    </model>
  </world>
</sdf>
""" % (os.path.basename(sys.argv[1]), int(occ.sum()), int(kept.sum()), len(rects), "\n".join(links))
    open(sys.argv[2], "w").write(world)
    print("occupied %d, kept %d, boxes %d -> %s" % (occ.sum(), kept.sum(), len(rects), sys.argv[2]))


if __name__ == "__main__":
    main()
